### ISSUE TITLE
You did not mention your e-dad :(

### ISSUE THREAD

**Issue by rhygg** [cosmxc/cosmxc#1]
very bad girl, i is sad, i is crying

**Comment by null8626** [comment]
where me :(

**Comment by rhygg** [comment]
so true, we need answers. e-son and e-dad need to be mentioned

**Comment by magmabits** [comment]
where e-brother :c

**Comment by null8626** [comment]
smh >:(

**Comment by dev-bun** [comment]
**#e-dadlivesmatter**

**Comment by cosmxc** [comment]
:ded:

**Comment by rhygg** [comment]
mention e-family or else sad :(

**Comment by dev-bun** [comment]
plz do this, am crying because no efamily 😡

**Comment by cosmxc** [comment]
e-family it is. Send me the list of members :kek:

**Comment by cosmxc** [comment]
e-family it is. Send me the list of members :kek:

**Comment by null8626** [comment]
null as e-son :)

**Comment by dev-bun** [comment]
bun as e-bun
